/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardSearch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parse_c771638b640c41ffeb1091fb1d13c73f/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}
